// ClientApp/src/views/iot/alarms/alarmlist.vue
<template>
  <div class="system-list-container">
    <el-card shadow="hover">
      <div class="system-dept-search mb15">
        <el-form size="default" label-width="100px" class="mt35 mb35">
          <el-row :gutter="35">
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="警告创建时间">
                <el-date-picker
                  v-model="AckDateTime"
                  type="daterange"
                  start-placeholder="开始时间"
                  end-placeholder="结束时间"
                />
              </el-form-item>
            </el-col>
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="清除时间">
                <el-date-picker
                  v-model="ClearDateTime"
                  type="daterange"
                  start-placeholder="开始时间"
                  end-placeholder="结束时间"
                />
              </el-form-item>
            </el-col>
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="警告持续开始时间">
                <el-date-picker
                  v-model="StartDateTime"
                  type="daterange"
                  start-placeholder="开始时间"
                  end-placeholder="结束时间"
                />
              </el-form-item>
            </el-col>
          </el-row>

          <el-row :gutter="35">
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="警告结束时间">
                <el-date-picker
                  v-model="EndDateTime"
                  type="daterange"
                  start-placeholder="开始时间"
                  end-placeholder="结束时间"
                />
              </el-form-item>
            </el-col>
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="告警类型">
                <el-input v-model="AlarmType" placeholder="请输入告警类型" />
              </el-form-item>
            </el-col>
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="告警状态">
                <el-select v-model="alarmStatus" placeholder="请选择告警状态">
                  <el-option
                    v-for="item in alarmStatusoptions"
                    :key="item.value"
                    :label="item.label"
                    :value="item.value"
                  />
                </el-select>
              </el-form-item>
            </el-col>
          </el-row>

          <el-row :gutter="35">
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="告警级别">
                <el-select v-model="serverity" placeholder="请选择告警级别">
                  <el-option
                    v-for="item in serverityoptions"
                    :key="item.value"
                    :label="item.label"
                    :value="item.value"
                  />
                </el-select>
              </el-form-item>
            </el-col>
            <el-col :xs="24" :sm="12" :md="8" :lg="8" :xl="8" class="mb20">
              <el-form-item label="起因来源">
                <el-select v-model="originatorType" placeholder="请选择起因来源">
                  <el-option
                    v-for="item in originatorTypeoptions"
                    :key="item.value"
                    :label="item.label"
                    :value="item.value"
                  />
                </el-select>
              </el-form-item>
            </el-col>
          </el-row>
        </el-form>

        <el-button size="default" type="primary" class="ml10" @click="getData()">
          <el-icon>
            <ele-Search />
          </el-icon>
          查询
        </el-button>
      </div>
      <el-table :data="tableData.rows" style="width: 100%" row-key="id">
        <el-table-column
          prop="alarmType"
          label="告警类型"
          show-overflow-tooltip
        ></el-table-column>

        <el-table-column
          prop="ackDateTime"
          label="创建时间"
          show-overflow-tooltip
        ></el-table-column>
        <el-table-column
          prop="startDateTime"
          label="警告持续的开始时间"
          show-overflow-tooltip
        ></el-table-column>

        <el-table-column
          prop="endDateTime"
          label="警告持续的结束时间"
          show-overflow-tooltip
        ></el-table-column>

        <el-table-column
          prop="清除时间"
          label="警告持续的结束时间"
          show-overflow-tooltip
        ></el-table-column>

        <el-table-column prop="alarmStatus" label="告警状态" show-overflow-tooltip>
          <template #default="scope">
            <el-tag
              effect="dark"
              size="small"
              :color="alarmstatusTAG.get(scope.row.alarmStatus)?.color"
              disable-transitions
              >{{ alarmstatusTAG.get(scope.row.alarmStatus)?.text }}</el-tag
            >
          </template>
        </el-table-column>

        <el-table-column prop="serverity" label="严重程度" show-overflow-tooltip>
          <template #default="scope">
            <el-tag
              effect="dark"
              size="small"
              :color="serveritybadge.get(scope.row.serverity)?.color"
              disable-transitions
              >{{ serveritybadge.get(scope.row.serverity)?.text }}</el-tag
            >
          </template>
        </el-table-column>

        <el-table-column prop="originatorType" label="设备类型" show-overflow-tooltip>
          <template #default="scope">
            <el-tag
              effect="dark"
              size="small"
              :color="originatorTypeTAG.get(scope.row.originatorType)?.color"
              disable-transitions
              >{{ originatorTypeTAG.get(scope.row.originatorType)?.text }}</el-tag
            >
          </template>
        </el-table-column>

        <el-table-column label="操作" show-overflow-tooltip width="200">
          <template #default="scope">
            <el-button
              size="small"
              text
              type="primary"
              v-if="
                scope.row.alarmStatus === 'Active_UnAck' ||
                scope.row.alarmStatus === 'Cleared_UnAck'
              "
              @click="acquireAlarm(scope.row)"
              >确认告警</el-button
            >
            <el-button
              size="small"
              text
              type="primary"
              v-if="
                scope.row.alarmStatus === 'Active_Ack' ||
                scope.row.alarmStatus === 'Active_UnAck'
              "
              @click="clearAlarm(scope.row)"
              >清除告警</el-button
            >
          </template>
        </el-table-column>
      </el-table>
      <el-pagination
        @size-change="onHandleSizeChange"
        @current-change="onHandleCurrentChange"
        class="mt15"
        :pager-count="5"
        :page-sizes="[10, 20, 30]"
        v-model:current-page="tableData.param.pageNum"
        background
        v-model:page-size="tableData.param.pageSize"
        layout="total, sizes, prev, pager, next, jumper"
        :total="tableData.total"
      >
      </el-pagination>
    </el-card>

    <!-- <flowdesigner ref="flowdesignerRef" /> -->
  </div>
</template>

<script lang="ts">
import { ref, toRefs, reactive, onMounted, defineComponent } from "vue";
import {
  ElMessageBox,
  ElMessage,
  ElButton,
  ElCard,
  ElIcon,
  ElInput,
  ElPagination,
  ElTable,
  ElTableColumn,
} from "element-plus";

import { Session } from "/@/utils/storage";
import { getAlarmList, clear, acquire } from "/@/api/alarm";
import { appmessage } from "/@/api/iapiresult";
// 定义接口来定义对象的类型

interface TableDataRow {
  id?: string;
  ackDateTime?: string;
  alarmDetail?: string;
  alarmStatus?: string;
  alarmType?: string;
  clearDateTime?: string;
  endDateTime?: string;
  originator?: string;
  originatorId?: string;
  originatorType?: string;
  propagate?: string;
  serverity?: string;
}
interface TableDataState {
  tableData: {
    rows: Array<TableDataRow>;
    total: number;
    loading: boolean;
    param: {
      pageNum: number;
      pageSize: number;
    };
  };
}
export default defineComponent({
  name: "alarmlist",
  components: {},
  setup() {
    const alarmStatusoptions = [
      {
        value: "-1",
        label: "全部",
      },
      {
        value: "0",
        label: "激活未应答",
      },
      {
        value: "1",
        label: "激活已应答",
      },
      {
        value: "2",
        label: "清除未应答",
      },
      {
        value: "3",
        label: "清除已应答",
      },
    ];

    const serverityoptions = [
      {
        value: "-1",
        label: "全部",
      },
      {
        value: "0",
        label: "不确定",
      },
      {
        value: "1",
        label: "警告",
      },
      {
        value: "2",
        label: "次要",
      },
      {
        value: "3",
        label: "重要",
      },
      {
        value: "4",
        label: "错误",
      },
    ];

    const originatorTypeoptions = [
      {
        value: "-1",
        label: "全部",
      },
      {
        value: "0",
        label: "未知",
      },
      {
        value: "1",
        label: "设备",
      },
      {
        value: "2",
        label: "网关",
      },
      {
        value: "3",
        label: "资产",
      },
    ];

    const serveritybadge = new Map([
      ["Indeterminate", { text: "不确定", color: "#8c8c8c" }],
      ["Warning", { text: "警告", color: "#faad14" }],
      ["Minor", { text: "次要", color: "#bae637" }],
      ["Major", { text: "主要", color: "#1890ff" }],
      ["Critical", { text: "错误", color: "#f5222d" }],
    ]);

    const alarmstatusTAG = new Map([
      ["Active_UnAck", { text: "激活未应答", color: "#ffa39e" }],
      ["Active_Ack", { text: "激活已应答", color: "#f759ab" }],
      ["Cleared_UnAck", { text: "清除未应答", color: "#87e8de" }],
      ["Cleared_Act", { text: "清除已应答", color: "#7cb305" }],
    ]);

    const originatorTypeTAG = new Map([
      ["Unknow", { text: "未知", color: "#ffa39e" }],
      ["Device", { text: "设备", color: "#f759ab" }],
      ["Gateway", { text: "网关", color: "#87e8de" }],
      ["Asset", { text: "资产", color: "#d3f261" }],
    ]);

    const userInfos = Session.get("userInfo");
    const router = useRouter();
    const state = reactive<TableDataState>({
      tableData: {
        rows: [],
        total: 0,
        loading: false,
        param: {
          pageNum: 1,
          pageSize: 10,
        },
      },
    });

    const query = reactive({
      AckDateTime: "",
      ClearDateTime: "",
      StartDateTime: "",
      EndDateTime: "",
      AlarmType: "",
      alarmStatus: "-1",
      serverity: "-1",
      originatorType: "-1",
      Originator: "",
    });
    const onHandleSizeChange = (val: number) => {
      state.tableData.param.pageSize = val;

      getData();
    };
    // 分页改变
    const onHandleCurrentChange = (val: number) => {
      state.tableData.param.pageNum = val;
      getData();
    };

    const clearAlarm = (row: TableDataRow) => {
      clear(row.id!).then((x:appmessage<boolean>) => {
        if (x && x.data) {
          ElMessage.success("清除成功");
          getData()
        } else {
          ElMessage.warning("清除失败:"+x.msg);
        }
      });
    };
    const acquireAlarm = (row: TableDataRow) => {
      acquire(row.id!).then((x:appmessage<boolean>) => {
       if (x && x.data) {
          ElMessage.success("确认成功");
          getData()
        } else {
          ElMessage.warning("确认失败"+x.msg);
        }
      });
    };
    const getData = () => {
      console.log(query);
      getAlarmList({
        offset: state.tableData.param.pageNum - 1,
        limit: state.tableData.param.pageSize,
        alarmStatus: query.alarmStatus,
        OriginatorId: "00000000-0000-0000-0000-000000000000",
        ClearDateTime: query.ClearDateTime,
        AckDateTime: query.AckDateTime,
        StartDateTime: query.StartDateTime,
        originatorType: query.originatorType,
        AlarmType: query.AlarmType,
        Name: "",
        EndDateTime: query.EndDateTime,
        OriginatorName: "",
        serverity: "-1",
      }).then((res) => {
        state.tableData.rows = res.data.rows;
        state.tableData.total = res.data.total;
      });
    };
    // 初始化表格数据
    const initTableData = () => {
      getData();
    };
    onMounted(() => {
      initTableData();
    });
    return {
      onHandleSizeChange,
      onHandleCurrentChange,
      getData,
      serveritybadge,
      alarmstatusTAG,
      originatorTypeTAG,
      alarmStatusoptions,
      originatorTypeoptions,
      serverityoptions,
      acquireAlarm,
      clearAlarm,
      ...toRefs(state),
      ...toRefs(query),
    };
  },
});
</script>

// IoTSharp/ClientApp/src/app/routes/device/alarmlist/alarmlist.component.ts
import { ChangeDetectorRef, Component, OnInit, TemplateRef, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { STPage, STReq, STRes, STComponent, STColumnTag, STColumn, STData, STColumnBadge } from '@delon/abc/st';
import { _HttpClient, ModalHelper, SettingsService } from '@delon/theme';
import { Guid } from 'guid-typescript';
import { NzDrawerService } from 'ng-zorro-antd/drawer';
import { NzMessageService } from 'ng-zorro-antd/message';
import { debounceTime } from 'rxjs/operators';
import { AppMessage } from '../../common/AppMessage';
import { AlarmdetailComponent } from '../alarmdetail/alarmdetail.component';

@Component({
  selector: 'app-alarmlist',
  templateUrl: './alarmlist.component.html',
  styleUrls: ['./alarmlist.component.less']
})
export class AlarmlistComponent implements OnInit {
  originators: originator[] = [];
  page: STPage = {
    front: false,
    total: true,
    zeroIndexed: true
  };
  q: {
    pi: number;
    ps: number;
    sorter: string;
    status: number | null;
    Name: string;
    AckDateTime: any;
    ClearDateTime: any;
    EndDateTime: any;
    StartDateTime: any;
    AlarmType: any;
    alarmStatus: any;
    OriginatorId: any;
    OriginatorName: string;
    serverity: any;
    originatorType: any;
  } = {
      pi: 0,
      ps: 10,
      Name: '',
      sorter: '',
      status: null,
      AckDateTime: null,
      ClearDateTime: null,
      StartDateTime: null,
      EndDateTime: null,
      AlarmType: '',
      OriginatorName: '',
      alarmStatus: '-1',
      OriginatorId: Guid.EMPTY,
      serverity: '-1',
      originatorType: '-1'
    };

  total = 0;
  data: any[] = [];
  loading = false;
  status = [
    { index: 1, text: '正常', value: false, type: 'default', checked: false },
    {
      index: 2,
      text: '已禁用',
      value: false,
      type: 'processing',
      checked: false
    },
    {
      index: -1,
      text: '已删除',
      value: false,
      type: 'processing',
      checked: false
    }
  ];

  url = 'api/alarm/list';
  req: STReq = { method: 'POST', allInBody: true, reName: { pi: 'offset', ps: 'limit' }, params: this.q };

  // 定义返回的参数
  res: STRes = {
    reName: {
      total: 'data.total',
      list: 'data.rows'
    }
  };

  @ViewChild('st', { static: true })
  st!: STComponent;

  serveritybadge: STColumnTag = {
    'Indeterminate': { text: '不确定', color: '#8c8c8c' },
    'Warning': { text: '警告', color: '#faad14' },
    'Minor': { text: '次要', color: '#bae637' },
    'Major': { text: '主要', color: '#1890ff' },
    'Critical': { text: '错误', color: '#f5222d' }
  };

  alarmstatusTAG: STColumnTag = {
    'Active_UnAck': { text: '激活未应答', color: '#ffa39e' },
    'Active_Ack': { text: '激活已应答', color: '#f759ab' },
    'Cleared_UnAck': { text: '清除未应答', color: '#87e8de' },
    'Cleared_Act': { text: '清除已应答', color: '#d3f261' }
  };
  originatorTypeTAG: STColumnTag = {
    'Unknow': { text: '未知', color: '#ffa39e' },
    'Device': { text: '设备', color: '#f759ab' },
    'Gateway': { text: '网关', color: '#87e8de' },
    'Asset': { text: '资产', color: '#d3f261' }
  };


  ServerityTAG: STColumnTag = {
    AccessToken: { text: 'AccessToken', color: 'green' },
    X509Certificate: { text: 'X509Certificate', color: 'blue' }
  };

  columns: STColumn[] = [
    { title: '', index: 'Id', type: 'checkbox' },
    // { title: 'id', index: 'id' },
    {
      title: '告警类型',
      index: 'alarmType'
    },
    { title: '创建时间', index: 'ackDateTime', type: 'date' },
    { title: '警告持续的开始时间', index: 'startDateTime', type: 'date' },
    { title: '警告持续的结束时间', index: 'endDateTime', type: 'date' },
    { title: '清除时间', index: 'clearDateTime', type: 'date' },
    { title: '告警状态', index: 'alarmStatus', type: 'tag', tag: this.alarmstatusTAG },
    { title: '严重程度', index: 'serverity', type: 'tag', tag: this.serveritybadge },

    { title: '设备类型', index: 'originatorType', type: 'tag', tag: this.originatorTypeTAG },

    {
      title: '操作', index: 'Id', buttons: [

        {
          text: '确认告警',
          pop: {
            title: '确认告警?',
            okType: 'primary',
            icon: 'warning'
          },
          click: (item: any) => {

            this.acquireAlarm(item);

          
          }, iif: record => record.alarmStatus === 'Active_UnAck' || record.alarmStatus === 'Cleared_UnAck',
        }, {
          text: '清除告警',
          pop: {
            title: '清除告警?',
            okType: 'dashed',
            icon: 'warning'
          },
          iif: record => record.alarmStatus === 'Active_Ack' || record.alarmStatus === 'Active_UnAck',
          click: (item: any) => {

            this.clearAlarm(item);
          }
        },

        ]
    },
  ];
  selectedRows: STData[] = [];
  description = '';
  totalCallNo = 0;
  expandForm = false;
  constructor(
    private http: _HttpClient,
    public msg: NzMessageService,
    private modal: ModalHelper,
    private cdr: ChangeDetectorRef,
    private _router: Router,
    private drawerService: NzDrawerService,
    private settingService: SettingsService
  ) { }

  ngOnInit() { }

  onOriginatorTypeChange($event) {
    this.q.OriginatorName = '';
    this.q.OriginatorId = Guid.EMPTY;
    this.originators = [];
  }

  onOriginatorInput($event) {
    var element = $event.target as HTMLInputElement;

    this.http
      .post('api/alarm/originators', {
        originatorName: element?.value ?? '',
        OriginatorType: this.q.originatorType
      })
      .pipe(debounceTime(500))
      .subscribe(
        next => {
          this.originators = [
            ...next.data.map(x => {
              return { id: x.id, name: x.name };
            })
          ];
        },
        error => { },
        () => { }
      );
  }

  clearAlarm(item) {
    this.http.post('api/alarm/clearAlarm',
      {
        id:item.id,
      }).subscribe(next => {

      if (next?.data) {
        this.getData();
      }
    }, error => {},()=>{});
  }

  acquireAlarm(item) {
    this.http.post('api/alarm/ackAlarm',
      {
        id: item.id,
      }).subscribe(next => {

      if (next?.data) {
        this.getData();
      }
    }, error => { }, () => { });
  }



  onOriginatorChange($event) {
    this.q.OriginatorId = this.originators.find(c => c.name == $event)?.id;
  }





  getData() {
    console.log(this.q);
    this.st.req = this.req;
    this.st.load(this.st.pi);
  }

  add(tpl: TemplateRef<{}>) { }

  reset() {
    setTimeout(() => { }, 1000);
  }
  setstatus(number: number, status: number) { }
}

export interface originator {
  id: string;
  name: string;
}

<page-header [title]="'告警列表'">
    <nz-card [nzBordered]="false" class>
      <form nz-form class="search__form" action="search">
        <div nz-row [nzGutter]="{ xs: 8, sm: 8, md: 8, lg: 24, xl: 48, xxl: 48 }">
          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="CreateDate">警告创建时间</nz-form-label>
              <nz-form-control>
                <nz-range-picker [(ngModel)]="q.AckDateTime" [ngModelOptions]="{ standalone: true }"></nz-range-picker>
              </nz-form-control>
            </nz-form-item>
          </div>
          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="CreateDate">清除时间</nz-form-label>
              <nz-form-control>
                <nz-range-picker [(ngModel)]="q.ClearDateTime" [ngModelOptions]="{ standalone: true }"></nz-range-picker>
              </nz-form-control>
            </nz-form-item>
          </div>  <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="CreateDate">警告持续开始时间</nz-form-label>
              <nz-form-control>
                <nz-range-picker [(ngModel)]="q.StartDateTime" [ngModelOptions]="{ standalone: true }"></nz-range-picker>
              </nz-form-control>
            </nz-form-item>
          </div>  
          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="EndDateTime">警告结束时间</nz-form-label>
              <nz-form-control>
                <nz-range-picker [(ngModel)]="q.EndDateTime" [ngModelOptions]="{ standalone: true }"></nz-range-picker>
              </nz-form-control>
            </nz-form-item>
          </div>
          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="DeviceName">告警类型</nz-form-label>
              <nz-form-control>
                <input nz-input [(ngModel)]="q.AlarmType" placeholder="请输入告警类型"
                  [ngModelOptions]="{ standalone: true }" />
              </nz-form-control>
            </nz-form-item>
          </div>

          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="AlarmStatus">告警状态</nz-form-label>
              <nz-form-control>
                <nz-select  [(ngModel)]="q.alarmStatus" [ngModelOptions]="{ standalone: true }"  > 
                  <nz-option nzValue="-1" nzLabel="全部"></nz-option>
                  <nz-option nzValue="0" nzLabel="激活未应答"></nz-option>
                  <nz-option nzValue="1" nzLabel="激活已应答"></nz-option>
                  <nz-option nzValue="2" nzLabel="清除未应答" ></nz-option>
                  <nz-option nzValue="3" nzLabel="清除已应答" ></nz-option>
                </nz-select>
              </nz-form-control>
            </nz-form-item>
          </div>
          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="Serverity">告警级别</nz-form-label>
              <nz-form-control>
                <nz-select  [(ngModel)]="q.serverity" [ngModelOptions]="{ standalone: true }" > 
                  <nz-option nzValue="-1" nzLabel="全部"></nz-option>
                  <nz-option nzValue="0" nzLabel="不确定"></nz-option>
                  <nz-option nzValue="1" nzLabel="警告"></nz-option>
                  <nz-option nzValue="2" nzLabel="次要" ></nz-option>
                  <nz-option nzValue="3" nzLabel="重要" ></nz-option>
                  <nz-option nzValue="4" nzLabel="错误" ></nz-option>
                </nz-select>
              </nz-form-control>
            </nz-form-item>
          </div>
          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="OriginatorType">起因来源</nz-form-label>
              <nz-form-control>
                <nz-select  [(ngModel)]="q.originatorType" (ngModelChange)="onOriginatorTypeChange($event)" [ngModelOptions]="{ standalone: true }" > 
                  <nz-option nzValue="-1" nzLabel="全部"></nz-option>
                  <nz-option nzValue="0" nzLabel="未知"></nz-option>
                  <nz-option nzValue="1" nzLabel="设备"></nz-option>
                  <nz-option nzValue="2" nzLabel="网关" ></nz-option>
                  <nz-option nzValue="3" nzLabel="资产" ></nz-option>
                </nz-select>
              </nz-form-control>
            </nz-form-item>
          </div>
          <div nz-col nzMd="8" nzSm="24">
            <nz-form-item>
              <nz-form-label nzFor="DeviceName">起因对象</nz-form-label>
              <nz-form-control>
                <input nz-input [(ngModel)]="q.OriginatorName" (input)="onOriginatorInput($event)" (ngModelChange)="onOriginatorChange($event)" name="Originator" placeholder="请输入"  [nzAutocomplete]="auto"/>
                <input type="hidden" [(ngModel)]="q.OriginatorId"  name="OriginatorId" placeholder="请输入"  />
                <nz-autocomplete #auto>
                  <nz-auto-option *ngFor="let option of originators" [nzValue]="option.name">{{ option.name }}</nz-auto-option>
                </nz-autocomplete>
              </nz-form-control>
            </nz-form-item>
          </div>
          <div nz-col [nzSpan]="24" [class.text-right]="expandForm" style="text-align: right">
            <button nz-button type="submit" [nzType]="'primary'" (click)="getData()">搜索</button>
            <!--<button nz-button type="submit" (click)="getData()" [nzType]="'primary'" [nzLoading]="loading">查询</button>-->
            <button nz-button type="reset" (click)="reset()" class="mx-sm">重置</button>
          </div>
        </div>
      </form>
  
      <!-- <button nz-button [nzType]="'primary'" (click)="openComponent(-1)" acl [acl-ability]="59">
        <i nz-icon nzType="plus"></i>
        <span>{{ 'button.new' | i18n }}</span>
      </button> -->
      <!--<button nz-button [nzType]="'primary'" [routerLink]="['/manage/authority/roleform']" [queryParams]="{Id:-1}">
            <i nz-icon nzType="plus"></i>
            <span>{{ 'button.new' | translate }}</span>
          </button>-->
  
      <st
        #st
        [columns]="columns"
        [data]="url"
        ps="20"
        [page]="page"
        [req]="req"
        [res]="res"
        [expand]="expand"
        expandRowByClick
        expandAccordion
     
      >
        <ng-template #expand let-item let-index="index" let-column="column">
          <nz-card nzTitle="告警详情">
            {{item.alarmDetail}}
          </nz-card>

          <nz-card nzTitle="起因对象">
            <sv-container col="2">
              <sv label="id" type="primary">  {{item?.originator?.id}}</sv>
              <sv label="名称" type="success">  {{item?.originator?.name}}</sv>
            </sv-container>
          </nz-card>


          
        </ng-template>
      </st>
    </nz-card>
    <ng-template #modalContent>
      <nz-form-item>
        <nz-form-label nzFor="no">描述</nz-form-label>
        <nz-form-control>
          <input nz-input [(ngModel)]="description" name="description" placeholder="请输入" id="no" />
        </nz-form-control>
      </nz-form-item>
    </ng-template>
  </page-header>
