// IoTSharp/ClientApp/src/app/routes/devices/devicegraph/devicegraph.component.ts
import { ChangeDetectorRef, Component, ComponentFactoryResolver, ElementRef, Input, OnInit, ViewChild } from '@angular/core';
import { Graph, Shape, NodeView } from '@antv/x6';
import { STComponent, STData } from '@delon/abc/st';
import { SettingsService } from '@delon/theme';
import { Subscription, timer } from 'rxjs';
import { DeviceItem, EdgeItem, IBizData, IToolsPanel, PanelItem, PortItem } from 'src/app/models/devicegraph/ibizdata';
import { Device, GateWay } from 'src/app/models/devicegraph/shape';
import { toolpaneldirective } from 'src/app/models/devicegraph/toolpaneldirective';
import { ConnectionedgeComponent } from './panels/connectionedge/connectionedge.component';
import { DevivceshapeComponent } from './panels/devivceshape/devivceshape.component';
import { GatewayshapeComponent } from './panels/gatewayshape/gatewayshape.component';
import { PortshapeComponent } from './panels/portshape/portshape.component';

@Component({
  selector: 'app-devicegraph',
  templateUrl: './devicegraph.component.html',
  styleUrls: ['./devicegraph.component.less']
})
export class DevicegraphComponent implements OnInit {
  @ViewChild(toolpaneldirective, { static: true })
  toolpanelcontainer!: toolpaneldirective;
  portiseselected = false;
  //注册工具面板
  toolpanels = [
    new PanelItem<IToolsPanel>('device', DevivceshapeComponent, {}, null, false),
    new PanelItem<IToolsPanel>(
      'gateway',
      GatewayshapeComponent,
      {
        //  someneedtransferdata: "yourdata,don't forget declara a @Input someneedtransferdata Property ",
      },
      null,
      false
    ),
    new PanelItem<IToolsPanel>(
      'edge',
      ConnectionedgeComponent,
      {
        //  someneedtransferdata: "yourdata,don't forget declara a @Input someneedtransferdata Property ",
      },
      null,
      false
    ),

    new PanelItem<IToolsPanel>(
      'port',
      PortshapeComponent,
      {
        //  someneedtransferdata: "yourdata,don't forget declara a @Input someneedtransferdata Property ",
      },
      null,
      false
    )
  ];
  selectedstyle = {
    body: {
      stroke: '#00ff00',
      strokeWidth: 5
    }
  };
  selcetedDevice: any = {
    ports: {
      in: []
    }
  };
  ports: PortItem[] = [];
  selectedport = {
    port: {},
    owner: {},
    orginattr: {}
  };
  subscription: Subscription;
  droppedData: string;
  @Input()
  id: Number = -1;
  @ViewChild('container', { static: true })
  private container!: ElementRef;
  @ViewChild('st')
  private st: STComponent;
  data: Array<DeviceItem> = [
    {
      devicename: '设备1',
      id: '11',
      type: 'device',
      logo: 'control',
      image: './assets/logo.png',
      remark: '这是一个设备，拖动它放到设计器上',
      width: 0,
      height: 0,
      x: 0,
      y: 0,
      prop: {
        GraphStroke: '#d9d9d9',
        GraphStrokeWidth: 1,
        GraphTextFill: '',
        GraphTextFontSize: '',
        GraphPostionX: '',
        GraphPostionY: '',
        GraphFill: '',
        GraphTextRefX: '',
        GraphHeight: '',
        GraphTextRefY: '',
        GraphTextAnchor: '',
        GraphTextVerticalAnchor: '',
        GraphTextFontFamily: '',
        GraphWidth: '',
        GraphShape: ''
      },
      ports: {}
    },

    {
      devicename: '网关1',
      id: '44',
      type: 'gateway',
      logo: 'ungroup',
      image: './assets/logo.png',
      remark: '这是一个网关，拖动它放到设计器上',
      width: 0,
      height: 0,
      x: 0,
      y: 0,
      prop: {
        GraphStroke: '#d9d9d9',
        GraphStrokeWidth: 1,
        GraphTextFill: '',
        GraphTextFontSize: '',
        GraphPostionX: '',
        GraphPostionY: '',
        GraphFill: '',
        GraphTextRefX: '',
        GraphHeight: '',
        GraphTextRefY: '',
        GraphTextAnchor: '',
        GraphTextVerticalAnchor: '',
        GraphTextFontFamily: '',
        GraphWidth: '',
        GraphShape: ''
      },
      ports: {}
    },
    {
      devicename: '网关2',
      id: '55',
      type: 'gateway',
      logo: 'ungroup',
      image: './assets/logo.png',
      remark: '这是一个网关，拖动它放到设计器上',
      width: 0,
      height: 0,
      x: 0,
      y: 0,
      prop: {
        GraphStroke: '#d9d9d9',
        GraphStrokeWidth: 1,
        GraphTextFill: '',
        GraphTextFontSize: '',
        GraphPostionX: '',
        GraphPostionY: '',
        GraphFill: '',
        GraphTextRefX: '',
        GraphHeight: '',
        GraphTextRefY: '',
        GraphTextAnchor: '',
        GraphTextVerticalAnchor: '',
        GraphTextFontFamily: '',
        GraphWidth: '',
        GraphShape: ''
      },
      ports: {}
    },

    {
      devicename: '设备7',
      id: '99',
      type: 'device',
      logo: 'control',
      image: './assets/logo.png',
      remark: '这是一个设备，拖动它放到设计器上',
      width: 0,
      height: 0,
      x: 0,
      y: 0,
      prop: {
        GraphStroke: '#d9d9d9',
        GraphStrokeWidth: 1,
        GraphTextFill: '',
        GraphTextFontSize: '',
        GraphPostionX: '',
        GraphPostionY: '',
        GraphFill: '',
        GraphTextRefX: '',
        GraphHeight: '',
        GraphTextRefY: '',
        GraphTextAnchor: '',
        GraphTextVerticalAnchor: '',
        GraphTextFontFamily: '',
        GraphWidth: '',
        GraphShape: ''
      },
      ports: {}
    }
  ];

  graph!: Graph;
  magnetAvailabilityHighlighter = {
    name: 'stroke',
    args: {
      attrs: {
        fill: '#fff',
        stroke: '#47C769'
      }
    }
  };
  toolbtnclick = ({ cell }) => {
    this.data = [...this.data, cell.getProp('Biz')]; //设计器删除的设备返回设备列表
    this.graph.removeCell(cell);
  };
  tools: any = [
    {
      name: 'button',
      args: {
        markup: [
          {
            tagName: 'circle',
            selector: 'button',
            attrs: {
              r: 14,
              stroke: '#fe854f',
              strokeWidth: 2,
              fill: 'white',
              cursor: 'pointer'
            }
          },
          {
            tagName: 'text',
            textContent: '-',
            selector: 'icon',
            attrs: {
              fill: '#fe854f',
              fontSize: 24,
              textAnchor: 'middle',
              pointerEvents: 'none',
              y: '0.3em'
            }
          }
        ],
        x: '50%',
        y: '10%',
        offset: { x: -0, y: -0 },
        onClick: this.toolbtnclick
      }
    }
  ];
  constructor(
    cdr: ChangeDetectorRef,
    private settingService: SettingsService,
    private componentFactoryResolver: ComponentFactoryResolver
  ) {}

  newport(id) {
    this.selcetedDevice.ports.in = [...this.selcetedDevice.ports.in, { id: '0', portname: '新端口', type: 1, iotype: 1 }];
    console.log(this.selcetedDevice.ports.in);
  }

  private createpanel(panel: string, BizData: IBizData) {
    var _panel = this.toolpanels.find(c => c.name === panel);
    if (_panel.instance == null || !_panel.isselected) {
      const componentFactory = this.componentFactoryResolver.resolveComponentFactory(_panel?.component);
      const viewContainerRef = this.toolpanelcontainer.viewContainerRef;
      viewContainerRef.clear();
      const componentRef = viewContainerRef.createComponent<IToolsPanel>(componentFactory);
      componentRef.instance.BizData = BizData;
      _panel.instance = componentRef.instance;
      for (const iterator of this.toolpanels) {
        iterator.isselected = false;
      }
      _panel.isselected = true;
    }
    _panel.instance.BizData = BizData;
  }

  private submit(i: STData): void {
    this.updateEdit(i, false);
  }

  private updateEdit(i: STData, edit: boolean): void {
    this.st.setRow(i, { edit }, { refreshSchema: true });
  }
  ngOnInit(): void {
    this.graph = new Graph({
      container: this.container.nativeElement,
      selecting: {
        enabled: true,
        rubberband: true,
        showNodeSelectionBox: true
      },
      background: { color: '' },
      mousewheel: {
        enabled: true,
        zoomAtMousePosition: true,
        modifiers: 'alt',
        minScale: 0.5,
        maxScale: 10
      },
      resizing: true,
      rotating: true,
      autoResize: true,
      grid: true,
      height: 800,
      highlighting: {
        magnetAvailable: this.magnetAvailabilityHighlighter,
        magnetAdsorbed: {
          name: 'stroke',
          args: {
            attrs: {
              fill: '#fff',
              stroke: '#31d0c6'
            }
          }
        }
      },
      onPortRendered: args => {},
      connecting: {
        snap: true,
        allowBlank: false,
        allowLoop: false,
        highlight: true,
        connector: 'rounded',
        connectionPoint: 'boundary',
        router: {
          name: 'er',
          args: {
            direction: 'H'
          }
        },
        createEdge() {
          return new Shape.Edge({
            attrs: {
              line: {
                stroke: '#a0a0a0',
                strokeWidth: 1,
                targetMarker: {
                  name: 'classic',
                  size: 7
                }
              }
            }
          });
        },
        validateConnection({ sourceView, targetView, targetMagnet }) {
          if (!targetMagnet) {
            return false;
          }

          if (targetMagnet.getAttribute('port-group') !== 'in') {
            return false;
          }

          if (targetView) {
            const node = targetView.cell;
            if (node instanceof Device) {
              const portId = targetMagnet.getAttribute('port');
              const usedInPorts = node.getUsedInPorts(this);
              if (usedInPorts.find(port => port && port.id === portId)) {
                return false;
              }
            }
          }

          return true;
        }
      }
    });

    this.graph.on('edge:connected', ({ previousView, currentView, previousCell, currentCell, isNew, edge }) => {
      if (previousView) {
        this.update(previousView as NodeView);
      }
      if (currentView) {
        this.update(currentView as NodeView);
      }
      var targetcell = edge.getTargetCell();
      var sourcecell = edge.getSourceCell();
      var targetport = edge.getTargetPortId();
      var sourceport = edge.getSourcePortId();
      var td = targetcell.getProp('Biz') as DeviceItem;
      var sd = sourcecell.getProp('Biz') as DeviceItem;
      var g = sourcecell as unknown as Node;
      var d = targetcell as unknown as Node;
      var ip = d['getPort'](targetport);
      sourcecell['setPortProp'](sourceport, 'attrs/text', {
        text: ip.attrs.text.text
      });
      var sp = g['getPort'](sourceport);
      sp.attrs = { text: { text: 'dasd' } };
      console.log(sp);
    });

    this.graph.on('edge:added', ({ edge, index, options }) => {});

    this.graph.on('node:resized', ({ e, x, y, node, view }) => {
      var d = node.getProp('Biz') as DeviceItem;
      d.width = x;
      d.height = y;
      d.mateData = node;
      node.setProp('Biz', d);
      this.createpanel(d.type, d);
    });

    this.graph.on('node:moved', ({ e, x, y, node, view }) => {
      var d = node.getProp('Biz') as DeviceItem;
      d.x = x;
      d.y = y;
      d.mateData = node;
      node.setProp('Biz', d);
      this.createpanel(d.type, d);
    });

    this.graph.on('edge:click', ({ e, x, y, edge, view }) => {
      var _edge: EdgeItem = { id: edge.id, mateData: edge };
      this.createpanel('edge', _edge);
      // console.log(edge.getTargetNode());
      // console.log(edge.getSourceNode());
    });
    this.graph.on('blank:mousemove', ({ e }) => {
      this.dragEndlocation = e;
    });
    this.graph.on('edge:removed', ({ edge, options }) => {
      if (!options['ui']) {
        return;
      }

      const target = edge.getTargetCell();
      if (target instanceof Device) {
        target.updateInPorts(this.graph);
      }
      console.log(target);
    });

    this.graph.on('edge:mouseenter', ({ edge }) => {
      edge.addTools([
        'source-arrowhead',
        'target-arrowhead',
        {
          name: 'button-remove',
          args: {
            distance: -30
          }
        }
      ]);
    });

    this.graph.on('cell:click', ({ e, x, y, cell, view }) => {
      if (this.selectedport.port['id'] && this.selectedport.owner['id']) {
        var shape = this.graph.getCellById(this.selectedport.owner['id']);
        var md = shape.getProp('Biz') as DeviceItem;
        switch (md.type) {
          case 'device':
            {
              var d = shape as Device;
              switch (this.selectedport.port['group']) {
                case 'in':
                  d.setPortProp(this.selectedport.port['id'], 'attrs/circle', {
                    stroke: '#ff0000',
                    strokeWidth: 2
                  });
                  break;
                case 'out':
                  d.setPortProp(this.selectedport.port['id'], 'attrs/circle', {
                    stroke: '#3199FF',
                    strokeWidth: 2
                  });
                  break;
              }
            }

            break;

          case 'gateway':
            {
              var g = shape as GateWay;
              switch (this.selectedport.port['group']) {
                case 'in':
                  g.setPortProp(this.selectedport.port['id'], 'attrs/circle', {
                    stroke: '#ff0000',
                    strokeWidth: 2
                  });
                  break;
                case 'out':
                  g.setPortProp(this.selectedport.port['id'], 'attrs/circle', {
                    stroke: '#3199FF',
                    strokeWidth: 2
                  });
                  break;
              }
            }

            break;
        }
      }

      this.portiseselected = true;
      var matadata = cell.getProp('Biz') as DeviceItem;
      if (matadata) {
        switch (matadata.type) {
          case 'device':
            {
              if (e.target.attributes?.port?.value) {
                var device = cell as Device;
                var port = device.getPort(e.target.attributes.port.value);
                this.selectedport = {
                  port: port,
                  owner: device,
                  orginattr: port.attrs
                };
                device.setPortProp(port.id, 'attrs/circle', this.selectedstyle.body);
                timer(50).subscribe(next => {
                  var _port: PortItem = {
                    id: port.id,
                    mateData: port,
                    parentRef: device
                  };
                  this.createpanel('port', _port);
                });
              }
            }
            break;
          case 'gateway':
            {
              if (e.target.attributes?.port?.value) {
                var gateway = cell as GateWay;
                var port = gateway.getPort(e.target.attributes.port.value);
                this.selectedport = {
                  port: port,
                  owner: gateway,
                  orginattr: port.attrs
                };
                gateway.setPortProp(port.id, 'attrs/circle', this.selectedstyle.body);
                timer(50).subscribe(next => {
                  var _port: PortItem = {
                    id: port.id,
                    mateData: port,
                    parentRef: gateway
                  };
                  this.createpanel('port', _port);
                });
              }
            }
            break;
        }
      }

      this.portiseselected = false;
    });

    this.graph.on('cell:mousedown', ({ cell }) => {
      //  cell.removeTools(); //只读状态下移除Node中的操作按钮
    });

    this.graph.on('node:click', (e, x, y, node, view) => {
      var matadata = e.node.getProp('Biz') as DeviceItem;

      if (matadata) {
        if (!this.portiseselected) {
          matadata.devicename;
          matadata.mateData = e.node;
          this.createpanel(matadata.type, matadata);
        }
        this.graph.getNodes;

        for (var item of this.graph.getNodes()) {
          var _matadata = e.node.getProp('Biz');

          item.attr({
            root: {
              magnet: false
            },
            body: {
              fill: '#eeffee',
              stroke: _matadata.prop.GraphStroke,
              strokeWidth: _matadata.prop.GraphStrokeWidth
            }
          });
        }
        e.cell.attr(this.selectedstyle);
        this.selcetedDevice = matadata;
      }
    });
  }
  update(view: NodeView) {
    const cell = view.cell;
    if (cell instanceof Device) {
      cell.getInPorts().forEach(port => {
        const portNode = view.findPortElem(port.id!, 'portBody');
        view.unhighlight(portNode, {
          highlighter: this.magnetAvailabilityHighlighter
        });
      });
      cell.updateInPorts(this.graph);
    }
  }

  dragend($event) {}
  onDrop($event) {
    switch ($event.dropData.type) {
      case 'device':
        {
          var ports = [];
          if ($event.dropData.ports?.in) {
            for (var item of $event.dropData.ports?.in) {
              var port = {
                id: item.id,
                group: 'in',

                zIndex: 'auto',
                attrs: {
                  text: {
                    // 标签选择器
                    text: item.portname
                  }
                }
              };
              ports = [...ports, port];
            }
          }
          if ($event.dropData.ports?.out) {
            for (var item of $event.dropData.ports?.out) {
              var port = {
                id: item.id,
                group: 'out',
                zIndex: 'auto',
                attrs: {
                  text: {
                    text: item.portname
                  }
                }
              };
              ports = [...ports, port];
            }
          }
          $event.dropData.width = 160;
          $event.dropData.height = 80;

          $event.dropData.x = this.dragEndlocation.offsetX;
          $event.dropData.y = this.dragEndlocation.offsetY;
          var data = {
            label: $event.dropData.devicename,
            height: $event.dropData.height,
            width: $event.dropData.width,
            tools: this.tools,
            offsetX: $event.dropData.x,
            offsetY: $event.dropData.y,
            Biz: $event.dropData,

            portdata: {
              group: {
                in: {
                  label: {
                    position: 'left'
                  },
                  position: {
                    name: 'right'
                  },
                  attrs: {
                    portBody: {
                      magnet: 'passive',
                      r: 6,
                      stroke: '#ff0000',
                      fill: '#fff',
                      strokeWidth: 2
                    }
                  }
                },
                out: {
                  position: {
                    name: 'left'
                  },
                  label: {
                    position: 'right'
                  },
                  attrs: {
                    portBody: {
                      magnet: true,
                      r: 6,
                      fill: '#fff',
                      stroke: '#3199FF',
                      strokeWidth: 2
                    }
                  }
                }
              },
              ports: ports
            }
          };
          this.createshape(data, 'device');
        }
        break;

      case 'gateway':
        {
          var ports = [];
          if ($event.dropData.ports?.in) {
            for (var item of $event.dropData.ports?.in) {
              var port = {
                id: item.id,
                group: 'in',

                zIndex: 'auto',
                attrs: {
                  text: {
                    text: item.portname
                  }
                }
              };
              ports = [...ports, port];
            }
          }
          if ($event.dropData.ports?.out) {
            for (var item of $event.dropData.ports?.out) {
              var port = {
                id: item.id,
                group: 'out',

                zIndex: 'auto',
                attrs: {
                  text: {
                    text: item.portname
                  }
                }
              };
              ports = [...ports, port];
            }
          }
          $event.dropData.width = 240;
          $event.dropData.height = 200;

          $event.dropData.x = this.dragEndlocation.offsetX;
          $event.dropData.y = this.dragEndlocation.offsetY;
          var data = {
            label: $event.dropData.devicename,
            height: $event.dropData.height,
            width: $event.dropData.width,
            tools: this.tools,
            offsetX: $event.dropData.x,
            offsetY: $event.dropData.y,
            Biz: $event.dropData,
            portdata: {
              group: {
                in: {
                  label: {
                    position: 'left'
                  },
                  position: {
                    name: 'right'
                  },
                  attrs: {
                    portBody: {
                      magnet: 'passive',
                      r: 6,
                      stroke: '#ff0000',
                      fill: '#fff',
                      strokeWidth: 2
                    }
                  }
                },
                out: {
                  position: {
                    name: 'left'
                  },
                  label: {
                    position: 'right'
                  },
                  attrs: {
                    portBody: {
                      magnet: true,
                      r: 6,
                      fill: '#fff',
                      stroke: '#3199FF',
                      strokeWidth: 2
                    }
                  }
                }
              },
              ports: ports
            }
          };
          this.createshape(data, 'gateway');
        }
        break;
    }
  }

  createshape(data: any, type: string) {
    switch (type) {
      case 'gateway':
        var node = this.graph.addNode(
          new GateWay({
            label: data.label,
            tools: data.tools,
            imageUrl: data.Biz.image
          })
            .setProp('Biz', data.Biz)
            .resize(data.width, data.height)
            .position(this.dragEndlocation.offsetX, this.dragEndlocation.offsetY)
            .initports(data.portdata)
            .setAttrs({
              root: {
                magnet: false
              },
              body: {
                fill: '#3199FF',
                stroke: data.Biz.prop.GraphStroke,
                strokeWidth: data.Biz.prop.GraphStrokeWidth
              }
            })
          //   .updateInPorts(this.graph),
        );
        node.setPortLabelMarkup;
        this.data.splice(this.data.indexOf(data.Biz), 1);
        node.setAttrs({});

        break;
      case 'device':
        var node = this.graph.addNode(
          new Device({
            label: data.label,
            tools: data.tools,
            imageUrl: data.Biz.image
          })
            .setProp('Biz', data.Biz)
            .resize(data.width, data.height)
            .position(this.dragEndlocation.offsetX, this.dragEndlocation.offsetY)
            .initports(data.portdata)
            .setAttrs({
              root: {
                magnet: false
              },
              body: {
                fill: '#3199FF',
                stroke: data.Biz.prop.GraphStroke,
                strokeWidth: data.Biz.prop.GraphStrokeWidth
              }
            })
        );
        node.setPortLabelMarkup;
        this.data.splice(this.data.indexOf(data.Biz), 1);
        node.setAttrs({});
        break;
    }
  }

  dragEnd(event) {}

  onmove($event) {
    this.dragEndlocation = $event;
  }

  dragEndlocation: any;

  loadsense() {}

  savesense() {
    var edges = this.graph.getEdges();
    var nodes = this.graph.getNodes();
    var shapes = [];
    var mappings = [];
    for (var item of nodes) {
      var port = item.ports.items;
      var incomes = port.filter(x => x.group === 'in').map(x => x.id);
      var outgoings = port.filter(x => x.group === 'out').map(x => x.id);
      var data = item.getProp('Biz');
      var dev = {
        incomes,
        outgoings,

        prop: {
          position: item.getPosition(),
          size: item.getSize(),
          body: item.getAttrs()['body'],
          text: item.getAttrs()['text']
        },
        id: data.id,
        type: data.type
      };
      shapes = [...shapes, dev];
    }

    for (var _item of edges) {
      var edge = {
        id: _item.id,
        source: _item.source,
        target: _item.target
      };
      mappings = [...mappings, edge];
    }

    var graph = {
      shapes,
      mappings
    };

    console.log(graph);
  }
}

<nz-header nzTheme="light" style="background-color: yellowgreen">
  <button nz-button nzType="primary" nzShape="round" (click)="savesense()">保存<i nz-icon nzType="download"></i></button>
</nz-header>
<nz-layout class="inner-layout" style="padding: 10px">
  <nz-sider nzWidth="200px" nzTheme="light">
    <nz-list nzItemLayout="horizontal" style="float: left; width: 200px; padding: 3px">
      <nz-list-item *ngFor="let item of data">
        <nz-list-item-meta
          [dropData]="item"
          mwlDraggable
          (dragEnd)="dragEnd($event)"
          draggable="true"
          [nzAvatar]="item.image"
          [nzDescription]="item.remark"
        >
          <nz-list-item-meta-title>
            <a href="#">{{ item.devicename }}</a>
          </nz-list-item-meta-title>
        </nz-list-item-meta>
      </nz-list-item>
    </nz-list>
  </nz-sider>
  <nz-content class="inner-content">
    <div
      #container
      class="container"
      mwlDroppable
      (drop)="onDrop($event)"
      (document:mousemove)="onmove($event)"
      style="float: left; width: 100%"
    ></div>
  </nz-content>
  <nz-sider nzTheme="light" nzWidth="500px" style="padding: 1rem">
    <ng-template toolpanelcontainer> </ng-template>
  </nz-sider>
</nz-layout>

// ClientApp/Vue/src/views/iotsharp/device/devicegraph.vue
<template>
  <div class="x6-graph-wrap">

 
    <div ref="container" class="x6-graph"></div>
  </div>
</template>

<script lang="ts">
  import { Graph, Edge, Shape, NodeView } from '@antv/x6';
  import { defineComponent, ref } from 'vue'; // reactive
  const magnetAvailabilityHighlighter = {
    name: 'stroke',
    args: {
      attrs: {
        fill: '#fff',
        stroke: '#47C769',
      },
    },
  };
  export default defineComponent({
    name: 'Index',
    setup() {
      const canUndo = ref(true);
      const canRedo = ref(false);
      // eslint-disable-next-line
      const history = ref(undefined as any);
      const graph = ref(Graph);
      const init: (any) => void = (that) => {
        // const graph = new Graph({
        //   container: that.$refs.container as HTMLDivElement,
        //   width: 800,
        //   height: 600,
        //   grid: true,
        //   history: true,
        // });

        that.graph = new Graph({
          grid: true,
          container: that.$refs.container as HTMLDivElement,
          width: 800,
          height: 600,
          highlighting: {
            magnetAvailable: magnetAvailabilityHighlighter,
            magnetAdsorbed: {
              name: 'stroke',
              args: {
                attrs: {
                  fill: '#fff',
                  stroke: '#31d0c6',
                },
              },
            },
          },
          connecting: {
            snap: true,
            allowBlank: false,
            allowLoop: false,
            highlight: true,
            connector: 'rounded',
            connectionPoint: 'boundary',
            router: {
              name: 'er',
              args: {
                direction: 'V',
              },
            },
            createEdge() {
              return new Shape.Edge({
                attrs: {
                  line: {
                    stroke: '#a0a0a0',
                    strokeWidth: 1,
                    targetMarker: {
                      name: 'classic',
                      size: 7,
                    },
                  },
                },
              });
            },
            validateConnection({ sourceView, targetView, targetMagnet }) {
              if (!targetMagnet) {
                return false;
              }

              if (targetMagnet.getAttribute('port-group') !== 'in') {
                return false;
              }

              if (targetView) {
                const node = targetView.cell;
                if (node instanceof Device) {
                  const portId = targetMagnet.getAttribute('port');
                  const usedInPorts = node.getUsedInPorts(this);
                  if (usedInPorts.find((port) => port && port.id === portId)) {
                    return false;
                  }
                }
              }

              return true;
            },
          },
        });

        that.graph.addNode(
          new Device().resize(120, 40).position(200, 50).updateInPorts(that.graph)
        );

        that.graph.addNode(
          new Device().resize(120, 40).position(400, 50).updateInPorts(that.graph)
        );

        that.graph.addNode(
          new GateWay().resize(120, 40).position(300, 250).updateInPorts(that.graph)
        );
        that.graph.addNode(
          new Device().resize(120, 40).position(300, 50).updateInPorts(that.graph)
        );
        that.graph.addNode(
          new Device().resize(120, 40).position(400, 50).updateInPorts(that.graph)
        );

        //  this.graph.fromJSON(this.data);

        that.graph.on('edge:connected', ({ previousView, currentView }) => {
          if (previousView) {
            update(previousView as NodeView);
          }
          if (currentView) {
            update(currentView as NodeView);
          }
          console.log(previousView);
        });

        that.graph.on('edge:removed', ({ edge, options }) => {
          if (!options.ui) {
            return;
          }

          const target = edge.getTargetCell();
          if (target instanceof Device) {
            target.updateInPorts(that.graph);
          }
          console.log(target);
        });

        that.graph.on('edge:mouseenter', ({ edge }) => {
          edge.addTools([
            'source-arrowhead',
            'target-arrowhead',
            {
              name: 'button-remove',
              args: {
                distance: -30,
              },
            },
          ]);
          console.log(edge);
        });

        that.graph.on('edge:mouseleave', ({ edge }) => {
          edge.removeTools();
        });
      };

      const update: (view: NodeView) => void = (view: NodeView) => {
        const cell = view.cell;
        if (cell instanceof Device) {
          cell.getInPorts().forEach((port) => {
            const portNode = view.findPortElem(port.id!, 'portBody');
            view.unhighlight(portNode, {
              highlighter: magnetAvailabilityHighlighter,
            });
          });
          console.log(graph);
          cell.updateInPorts(graph.value);
        }
      };
      const onUndo: () => void = () => {
        history.value.undo();
      };
      const onRedo: () => void = () => {
        history.value.redo();
      };

      return {
        canUndo,
        canRedo,
        history,
        init,
        onUndo,
        onRedo,
        update,
        graph,
      };
    },
    mounted() {
      /* eslint-disable */
      const that = this as any;
      this.$nextTick(function () {
        that.init(that);
      });
    },
  });

  class Device extends Shape.Rect {
    getInPorts() {
      return this.getPortsByGroup('in');
    }

    getOutPorts() {
      return this.getPortsByGroup('out');
    }

    getUsedInPorts(graph: Graph) {
      const incomingEdges = graph.getIncomingEdges(this) || [];
      return incomingEdges.map((edge: Edge) => {
        const portId = edge.getTargetPortId();
        return this.getPort(portId!);
      });
    }

    getNewInPorts(length: number) {
      return Array.from(
        {
          length,
        },
        () => {
          return {
            group: 'in',
          };
        }
      );
    }

    updateInPorts(graph: Graph) {
      const minNumberOfPorts = 1;
      const ports = this.getInPorts();
      const usedPorts = this.getUsedInPorts(graph);
      const newPorts = this.getNewInPorts(Math.max(minNumberOfPorts - usedPorts.length, 1));

      if (ports.length === minNumberOfPorts && ports.length - usedPorts.length > 0) {
        // noop
      } else if (ports.length === usedPorts.length) {
        this.addPorts(newPorts);
      } else if (ports.length + 1 > usedPorts.length) {
        this.prop(['ports', 'items'], this.getOutPorts().concat(usedPorts).concat(newPorts), {
          rewrite: true,
        });
      }

      return this;
    }
  }
  Device.config({
    attrs: {
      root: {
        magnet: false,
      },
      body: {
        fill: '#f5f5f5',
        stroke: '#d9d9d9',
        strokeWidth: 1,
      },
    },
    ports: {
      items: [
        {
          group: 'out',
        },
      ],
      groups: {
        in: {
          position: {
            name: 'top',
          },
          attrs: {
            portBody: {
              magnet: 'passive',
              r: 6,
              stroke: '#ffa940',
              fill: '#fff',
              strokeWidth: 2,
            },
          },
        },
        out: {
          position: {
            name: 'bottom',
          },
          attrs: {
            portBody: {
              magnet: true,
              r: 6,
              fill: '#fff',
              stroke: '#3199FF',
              strokeWidth: 2,
            },
          },
        },
      },
    },
    portMarkup: [
      {
        tagName: 'circle',
        selector: 'portBody',
      },
    ],
  });

  class GateWay extends Shape.Rect {
    getInPorts() {
      return this.getPortsByGroup('in');
    }

    getOutPorts() {
      return this.getPortsByGroup('out');
    }

    getUsedInPorts(graph: Graph) {
      const incomingEdges = graph.getIncomingEdges(this) || [];
      return incomingEdges.map((edge: Edge) => {
        const portId = edge.getTargetPortId();
        return this.getPort(portId!);
      });
    }

    getNewInPorts(length: number) {
      return Array.from(
        {
          length,
        },
        () => {
          return {
            group: 'in',
          };
        }
      );
    }

    updateInPorts(graph: Graph) {
      const minNumberOfPorts = 8;
      const ports = this.getInPorts();
      const usedPorts = this.getUsedInPorts(graph);
      const newPorts = this.getNewInPorts(Math.max(minNumberOfPorts - usedPorts.length, 1));

      if (ports.length === minNumberOfPorts && ports.length - usedPorts.length > 0) {
        // noop
      } else if (ports.length === usedPorts.length) {
        this.addPorts(newPorts);
      } else if (ports.length + 1 > usedPorts.length) {
        this.prop(['ports', 'items'], this.getOutPorts().concat(usedPorts).concat(newPorts), {
          rewrite: true,
        });
      }

      return this;
    }
  }
  GateWay.config({
    attrs: {
      root: {
        magnet: false,
      },
      body: {
        fill: '#ffa940',
        stroke: '#d9d9d9',
        strokeWidth: 1,
      },
    },
    ports: {
      items: [
        {
          group: 'out',
        },
      ],
      groups: {
        in: {
          position: {
            name: 'top',
          },
          attrs: {
            portBody: {
              magnet: 'passive',
              r: 6,
              stroke: '#ffa940',
              fill: '#fff',
              strokeWidth: 2,
            },
          },
        },
        out: {
          position: {
            name: 'bottom',
          },
          attrs: {
            portBody: {
              magnet: true,
              r: 6,
              fill: '#fff',
              stroke: '#3199FF',
              strokeWidth: 2,
            },
          },
        },
      },
    },
    portMarkup: [
      {
        tagName: 'circle',
        selector: 'portBody',
      },
    ],
  });
</script>

<style scoped></style>
