// IoTSharp/ClientApp/src/app/routes/produce/produceform/produceform.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-produceform',
  templateUrl: './produceform.component.html',
  styleUrls: ['./produceform.component.less']
})
export class ProduceformComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<page-header [breadcrumb]="phNgContent" [title]="title">
    <ng-template #phNgContent class> </ng-template>
    <nz-card [nzBordered]="false">
      <form nz-form [formGroup]="form" (ngSubmit)="submit()" se-container="1" labelWidth="200">
        <se label="名称" error="名称不能为空或者空白字符" required>
          <input nz-input formControlName="name" placeholder="名称" />
        </se>

        <se label="名称" error="图标" required>
          <input nz-input formControlName="icon" placeholder="图标" />
        </se>
        <se label="默认网关类型" error="默认网关类型" required>
          <nz-select formControlName="gatewayType" placeholder="默认网关类型">
            <nz-option nzValue="Unknow" nzLabel="Unknow"></nz-option>
            <nz-option nzValue="Customize" nzLabel="Customize"></nz-option>
            <nz-option nzValue="Modbus" nzLabel="Modbus"></nz-option>
            <nz-option nzValue="Bacnet" nzLabel="Bacnet"></nz-option>
            <nz-option nzValue="OPC_UA" nzLabel="OPC_UA"></nz-option>
            <nz-option nzValue="CanOpen" nzLabel="CanOpen"></nz-option>
          </nz-select>
        </se>

        <se label="默认网关配置" error="默认网关配置" *ngIf="this.form.value.gatewayType==='Customize'">
          <nz-code-editor formControlName="gatewayConfigurationJson" [class.full-screen]="fullScreen" 
          style="width: 100%; height: 500px; padding-top: 1rem" class="editor" 
          [nzEditorOption]="{ theme: 'vs',language: 'json' }">
        </nz-code-editor>
        </se>
        <se label="默认网关配置名称" error="默认网关配置名称" *ngIf="this.form.value.gatewayType!=='Unknow'&&this.form.value.gatewayType!=='Customize'">
          <input nz-input formControlName="gatewayConfigurationName" placeholder="默认网关配置名称" />
        </se>
        <se label="默认设备类型" error="默认设备类型" required>
          <nz-select formControlName="defaultDeviceType" placeholder="默认设备类型">
            <nz-option nzValue="Device" nzLabel="Device"></nz-option>
            <nz-option nzValue="Gateway" nzLabel="Gateway"></nz-option>
          </nz-select>
        </se>
        <se label="默认超时" error="默认超时" required>
          <nz-input-number formControlName="defaultTimeout" [nzMin]="0"  [nzStep]="1"></nz-input-number>
        </se>
        <se label="默认认证方式" error="认证方式" required>
          <nz-select formControlName="defaultIdentityType" placeholder="默认认证方式">
            <nz-option nzValue="AccessToken" nzLabel="AccessToken"></nz-option>
            <nz-option nzValue="X509Certificate" nzLabel="X509Certificate"></nz-option>
          </nz-select>
        </se>
        <se>
          <input nz-input formControlName="id" type="hidden" />
          <button nz-button type="reset" (click)="close()">取消</button>
          <button nz-button nzType="primary" [disabled]="form.invalid" type="submit" [nzLoading]="submitting">保存</button>
        </se>
      </form>


 
    </nz-card>
  </page-header>

// ClientApp/src/views/iot/produce/produceform.vue
<template>
  <div>
    <el-drawer v-model="drawer" :title="dialogtitle" size="75%">
      <div class="add-form-container">
        <el-form :model="dataForm" size="default" label-width="150px">
          <el-row :gutter="35">
            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" class="mb20">
              <el-form-item label="产品名称">
                <el-input
                  v-model="dataForm.name"
                  placeholder="请输入产品名称"
                  clearable
                ></el-input>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" class="mb20">
              <el-form-item label="产品名称">
                <el-input
                  v-model="dataForm.icon"
                  placeholder="请输入产品icon"
                  clearable
                ></el-input>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" class="mb20">
              <el-form-item label="默认网关类型">
                <el-select
                  v-model="dataForm.gatewayType"
                  placeholder="请选择默认网关类型"
                >
                  <el-option
                    v-for="item in gatewayTypes"
                    :key="item"
                    :label="item"
                    :value="item"
                  />
                </el-select>
              </el-form-item>
            </el-col>
            <el-col
              :xs="24"
              :sm="24"
              :md="24"
              :lg="24"
              :xl="24"
              class="mb20"
              v-if="dataForm.gatewayType === 'Customize'"
            >
              <el-form-item label="默认网关配置">
                <!-- <el-input
                  v-model="dataForm.gatewayConfigurationJson"
                  placeholder="请输入超时"
                  clearable
                ></el-input> -->

                <monaco height="300px" width="80%" theme="vs-dark" value="sss" language="json" selectOnLineNumbers="true"></monaco>
              </el-form-item>
            </el-col>

            <el-col
              :xs="24"
              :sm="24"
              :md="24"
              :lg="24"
              :xl="24"
              class="mb20"
              v-if="
                dataForm.gatewayType !== 'Unknow' && dataForm.gatewayType !== 'Customize'
              "
            >
              <el-form-item label="默认网关配置名称">
                <el-input
                  v-model="dataForm.gatewayConfigurationName"
                  placeholder="请输入默认网关配置名称"
                  clearable
                ></el-input>
              </el-form-item>
            </el-col>
            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" class="mb20">
              <el-form-item label="默认产品类型">
                <el-select
                  v-model="dataForm.defaultDeviceType"
                  placeholder="请选择认证方式"
                >
                  <el-option
                    v-for="item in deviceTypes"
                    :key="item"
                    :label="item"
                    :value="item"
                  />
                </el-select>
              </el-form-item>
            </el-col>
            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" class="mb20">
              <el-form-item label="默认超时">
                <el-input
                  v-model="dataForm.defaultTimeout"
                  placeholder="请输入默认超时"
                  clearable
                ></el-input>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" class="mb20">
              <el-form-item label="认证方式">
                <el-select
                  v-model="dataForm.defaultIdentityType"
                  placeholder="请选择认证方式"
                >
                  <el-option
                    v-for="item in identityTypes"
                    :key="item"
                    :label="item"
                    :value="item"
                  />
                </el-select>
              </el-form-item>
            </el-col>

            <el-col :xs="24" :sm="24" :md="24" :lg="24" :xl="24" class="mb20">
              <el-form-item>
                <el-button type="primary" @click="onSubmit">保存</el-button>
                <el-button @click="closeDialog">取消</el-button>
              </el-form-item>
            </el-col>
          </el-row>
        </el-form>
      </div>
    </el-drawer>


  </div>
</template>

<script lang="ts">
import { ref, toRefs, reactive, onMounted, defineComponent, watchEffect } from "vue";
import { ElMessageBox, ElMessage } from "element-plus";
import { deviceApi } from "/@/api/devices";
import { appmessage } from "/@/api/iapiresult";
import { getProduce } from "/@/api/produce";

import  monaco  from "/@/components/monaco/monaco.vue";

interface produceformdata {
  drawer: boolean;
  dialogtitle: string;
  dataForm: produceaddoreditdto;
  gatewayTypes: Array<string>;
  identityTypes: Array<string>;
  deviceTypes: Array<string>;
}

export default defineComponent({
  name: "produceform",
  components: {monaco},
  setup(props) {
    const state = reactive<produceformdata>({
      drawer: false,
      dialogtitle: "",
      gatewayTypes: ["Unknow", "Customize", "Modbus", "Bacnet", "OPC_UA", "CanOpen"],
      identityTypes: ["AccessToken", "DevicePassword", "X509Certificate"],
      deviceTypes: ["Device", "Gateway"],
      dataForm: {
        id: "0000000-0000-0000-0000-000000000000",
        name: "",
        icon: "",
        defaultTimeout: 300,
        gatewayType: "",
        gatewayConfigurationName: "",
        defaultDeviceType: "",
        gatewayConfigurationJson: "",
        defaultIdentityType: "",
      },
    });

    const openDialog = (produceid: string) => {
      if (produceid === "0000000-0000-0000-0000-000000000000") {
        state.dataForm = {
          id: "0000000-0000-0000-0000-000000000000",
          name: "",
          icon: "",
          defaultTimeout: 300,
          gatewayType: "",
          gatewayConfigurationName: "",
          defaultDeviceType: "",
          gatewayConfigurationJson: "",
          defaultIdentityType: "",
        };
        state.dialogtitle = "新增产品";
      } else {
        state.dialogtitle = "修改产品";
        getProduce(produceid).then((res) => {
          state.dataForm = res.data;
          if (
            state.dataForm.gatewayType !== "Unknow" &&
            state.dataForm.gatewayType !== "Customize"
          ) {
            state.dataForm.gatewayConfigurationName = res.data.gatewayConfiguration;
          } else if (state.dataForm.gatewayType === "Customize") {
            state.dataForm.gatewayConfigurationJson = res.data.gatewayConfiguration;
          }
        });
      }
      state.drawer = true;
    };
    // 关闭弹窗
    const closeDialog = () => {
      state.drawer = false;
    };

    watchEffect(() => {});

    onMounted(() => {});
    const onSubmit = () => {
      if (state.dataForm.id === "0000000-0000-0000-0000-000000000000") {
        deviceApi()
          .postdevcie(state.dataForm)
          .then((res: appmessage<boolean>) => {
            if (res.code === 10000 && res.data) {
              ElMessage.success("新增成功");
            } else {
              ElMessage.warning("新增失败:" + res.msg);
            }
          });
      } else {
        deviceApi()
          .putdevcie(state.dataForm)
          .then((res: appmessage<boolean>) => {
            if (res.code === 10000 && res.data) {
              ElMessage.success("修改成功");
            } else {
              ElMessage.warning("修改失败:" + res.msg);
            }
          });
      }
    };
    return { ...toRefs(state), onSubmit, openDialog, closeDialog };
  },
});
</script>
